### ISSUE TITLE
Unusual `hl-line` colors

### ISSUE THREAD

**Issue by lepieru** [m-cat/nimbus-theme#19]
The `hl-line` colors are not usual. It can be very confusing, at least for me.

Current:
- added line: yellow/orange
- modified line: purple
- removed line: red

More common choice:
- added line: green
- modified line: yellow/orange
- removed line: red

![Screenshot](http://i.imgur.com/KnJkYa1.png)

**Comment by m-cat** [comment]
Hey, thanks for the feedback. Looks like the colors were chosen for consistency with a different package, see PL #8. I see what you're saying though, I'll make the change and look into changing git-gutter as well.

**Comment by m-cat** [comment]
Pushed the fix, look good?

**Comment by lepieru** [comment]
Perfect!
