### ISSUE TITLE
Diff refine hard to read

### ISSUE THREAD

**Issue by lepieru** [m-cat/nimbus-theme#20]
A diffing with a refine face is hard to read.

This example below come from a `magit-status` where `# modified line` is the refine.

![Screenshot](http://i.imgur.com/hscpVNe.png)

**Comment by m-cat** [comment]
I agree that that looks terrible. Can you give me some advice on how to reproduce this? I'm not sure what a refine is in git.

**Comment by lepieru** [comment]
I named it a refine because it's the name of the faces variables (`diff-refine-*`, and more specificly `diff-refine-added` here).

In any case, this faces are used for the parts of a line which have been modified. You can enable it with this:

```el
(setq magit-diff-refine-hunk t)
; or
(setq magit-diff-refine-hunk `all) ; I use this one
```

`diff-refine-removed` is not as bad as `diff-refine-added` but can be better too (see screenshot below).

![Screenshot1](http://i.imgur.com/YirGZPJ.png)

I usually make foreground more flashy for the refines (like below). 

![Screenshot2](http://i.imgur.com/IyqimEk.png)

**Comment by m-cat** [comment]
Thanks a lot for the explanation! I pushed a change, can you let me know what you think? I tried making the foreground brighter but it wasn't clear enough for me, so I ended up just changing the highlight.

**Comment by lepieru** [comment]
It is readable for now. Using the same background color for the two is ok for me.

Just for be sure we agree, I post below a result for your work:

![Screenshot](http://i.imgur.com/ol0SnUw.png)
