### ISSUE TITLE
Compilation buffer with spaceline looks weird

### ISSUE THREAD

**Issue by matthew-piziak** [m-cat/nimbus-theme#26]
![screenshot](https://user-images.githubusercontent.com/6801001/54370968-f72fa900-464e-11e9-8905-e0bb50223e74.png)

**Comment by matthew-piziak** [comment]
I have confirmed that `nimbus` is the first theme being run, and I have no customizations of `compilation` faces.

**Comment by m-cat** [comment]
Thanks for reporting this! I just pushed a fix revamping the mode-line faces. Could you have another look and let me know what you think? Thanks again!

**Comment by matthew-piziak** [comment]
Perfect!

![screenshot](https://user-images.githubusercontent.com/6801001/54378368-8b087180-465d-11e9-8775-b90758f8b89b.png)

**Comment by m-cat** [comment]
Great! And thanks for sharing the before & after screenshots 😄

**Comment by matthew-piziak** [comment]
My pleasure! What great upstream service. :smile:
