### ISSUE TITLE
Theming for Notmuch views?

### ISSUE THREAD

**Issue by powellc** [m-cat/nimbus-theme#27]
I use notmuch to read email, and while I love nimbus, it does not have a shaded theme for emails which I have archived or read. This means I have to jump to another theme to read my email.

Any chance you can add notmuch support to Nimbus?

**Comment by m-cat** [comment]
Hey Powell! It's already on my todo list -- will try to get to it today 👍

**Comment by m-cat** [comment]
Unfortunately it looks like notmuch requires a lot of setup. Can you please send a screenshot of the offending face, or maybe provide your configuration?

**Comment by powellc** [comment]
@m-cat curiously, notmuch-emacs appears to have updated how it renders email state, and now the date column changes color to indicate state. So this is no longer an issue for me. Excellent theme, keep up the great work!
