### ISSUE TITLE
Themeing for Elfeed?

### ISSUE THREAD

**Issue by powellc** [m-cat/nimbus-theme#28]
Similar to my notmuch issue, Elfeed's "read" entries also does not have support which makes this theme difficult to use with Elfeed. Any help would be greatly appreciated!

**Comment by m-cat** [comment]
Hey, I'm not sure I understand. It looks like unread entries are bold whereas read entries are not. I don't use elfeed though, so if you could provide screenshots or reproduction steps it would help a lot. Thanks!

**Comment by powellc** [comment]
@m-cat  this was my bad. My font was incorrectly rendering bold. I'll close this request .. theme looks great :)
