### ISSUE TITLE
html, web-mode, color

### ISSUE THREAD

**Issue by n1rdeks** [m-cat/nimbus-theme#33]
Guys, i'm a new in emacs world.

Web-mode, editing html. Tag pairs color not visible.

![2021-01-15-225022_1920x1080_scrot(1)](https://user-images.githubusercontent.com/63796667/104772290-3f0c4380-5784-11eb-87d3-f42a6f022382.png)

**Comment by n1rdeks** [comment]
after  i add transparent this color is more visible,  but still not comfortable.


![2021-01-15-231816_1920x1080_scrot](https://user-images.githubusercontent.com/63796667/104774586-ffdff180-5787-11eb-984b-29a6c41454ee.png)

**Comment by m-cat** [comment]
> Guys, i'm a new in emacs world.

Welcome 👋🏻

I don't use web-mode. Can you please provide steps for reproducing your issue, including your configuration for web-mode?

**Comment by n1rdeks** [comment]
I just add this mode and enable this theme.

**Comment by m-cat** [comment]
Thanks, I just set `web-mode-enable-current-element-highlight` and was able to reproduce it. I am free now so I'll tackle the issue quickly.

**Comment by n1rdeks** [comment]
thx

**Comment by m-cat** [comment]
How's this?

<img width="296" alt="Screen Shot 2021-01-15 at 21 30 23" src="https://user-images.githubusercontent.com/6035856/104775622-8a1c5b80-5770-11eb-9f3e-d113cbc18144.png">

**Comment by n1rdeks** [comment]
and one more thing.

Foreground Color So shining, IMO. ;) Maybe we use #93a1a1..

>How's this? 
Cool.

**Comment by m-cat** [comment]
Pushed the fix!

> Foreground Color So shining, IMO. ;) Maybe we use #93a1a1?
Because for eyes white color nice choice only for short time. After, your eyes tired.

Thanks for the feedback, I may adjust the foreground. I am trying your suggestion and I like it so far. It might be slightly too dark but I'll play around with it over the next few days

**Comment by n1rdeks** [comment]
Thx again. Amazing speed of response. Good luck.

**Comment by n1rdeks** [comment]
j

**Comment by m-cat** [comment]
Hey, I found #93a1a1 a bit too dark. But going back to the old foreground I found it too bright 😅

I picked a color that's right in between your suggestion and old color: #AAB0AB. Let me know what you think. I'll probably stick with #AAB0AB, but if you prefer #93a1a1 feel free to keep using that 🙂

**Comment by n1rdeks** [comment]
I looking this color (#AAB0AB), nice choice. I like your color.  Theme better and better.

**Comment by m-cat** [comment]
Awesome 😁 Pushed the change
