### ISSUE TITLE
Screenshot fails to load

### ISSUE THREAD

**Issue by grtcdr** [m-cat/nimbus-theme#38]
The [screenshot](https://camo.githubusercontent.com/ef277bb159dbddf8f66aae799d3fcaa890dbc439580d9b9c40eeaea466f4771d/68747470733a2f2f736961736b792e6e65742f7641476e646f4468476973356a656d36742d4a72657239696853574b615569566838355978775a69494971396e77) in the README fails to load with the following error:

```
Non-Image content-type returned
```

I would personally place the screenshot in a more reliable location, i.e. the repository itself. 

This might make the repository a bit slower to clone, but it ensures that this won't happen again (I'm not sure why it would, though). In that case, I would recommend optimizing the image with `jpegoptim` or `pngquant` or converting it to a webp with `cwebp` for the best compression sizes.

**Comment by m-cat** [comment]
Done in 6b3b581de258d6d554b88f3c6d71ab24db4f0951. Thanks a lot!

> In that case, I would recommend optimizing the image with jpegoptim or pngquant or converting it to a webp with cwebp for the best compression sizes.

I used ImageOptim for a lossless size reduction, so as not to affect the quality at all.

**Comment by m-cat** [comment]
This was a good opportunity to take a new screenshot, as the theme tends to change with time - hopefully for the better. 😛

**Comment by grtcdr** [comment]
> This was a good opportunity to take a new screenshot, as the theme tends to change with time - hopefully for the better.

Agreed! This actually concided with my wanting to bring attention to Nimbus by writing about it. I've taken [a few screenshots of my own](https://grtcdr.tn/posts/2022-12-05.html), which use [Git LFS](https://git-lfs.github.com/) behind the scenes.

Thank you for your prompt action :)
